# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='nif')),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('num_aseguradora', models.CharField(max_length=20, null=True, verbose_name='num_aseguradora')),
                ('fecha_alta', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'uploads/')),
                ('especialidad', models.ManyToManyField(to='terapeutas.Especialidad')),
            ],
            options={
                'verbose_name': 'terapeuta',
                'verbose_name_plural': 'terapeutas',
            },
        ),
    ]
