# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='telefono',
            field=models.CharField(max_length=12, null=True, verbose_name='telefono'),
        ),
    ]
