# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0002_terapeuta_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeuta',
            name='fecha_alta',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
