# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0027_auto_20160311_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='titulo')),
                ('neto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='neto')),
                ('iva', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='iva')),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='bruto')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Direccion_Facturacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
    ]
