# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField(blank=True, verbose_name='concepto')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='neto')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='cantidad')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='descuento')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalles Facturas',
            },
        ),
        migrations.AlterField(
            model_name='factura',
            name='bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='bruto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='iva'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='neto'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='codigo_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Factura'),
        ),
    ]
