# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='iva',
            new_name='tipo_iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='bruto',
        ),
    ]
