# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20160312_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='sub_total'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='total'),
        ),
    ]
