# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='facturable',
            field=models.BooleanField(default=True, verbose_name='Facturable'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='tipo',
            field=models.CharField(choices=[(b'Entrevista', 'Entrevista'), (b'Sesion30', 'Sesion 30 minutos'), (b'Sesion45', 'Sesion 45 minutos')], max_length=9, null=True, verbose_name='tipo'),
        ),
    ]
