# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_auto_20160302_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiontipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='nombre')),
                ('facturable', models.BooleanField(default=True, verbose_name='Facturable')),
                ('coste', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='coste')),
            ],
            options={
                'verbose_name': 'sesion tipo',
                'verbose_name_plural': 'sesiones tipo',
            },
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='facturable',
        ),
        migrations.AlterField(
            model_name='sesion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sesiones.Sesiontipo'),
        ),
    ]
