# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='nif')),
            ],
            options={
                'verbose_name': 'tutor',
                'verbose_name_plural': 'tutores',
            },
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 31, 9, 41, 39, 977808, tzinfo=utc), verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nif',
            field=models.CharField(max_length=9, unique=True, verbose_name='nif'),
        ),
    ]
