# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20160131_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='nif')),
                ('pacientes', models.ManyToManyField(to='pacientes.Pacientes')),
            ],
            options={
                'verbose_name': 'tutor',
                'verbose_name_plural': 'tutores',
            },
        ),
        migrations.DeleteModel(
            name='tutor',
        ),
    ]
