# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20160131_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
        migrations.RenameModel(
            old_name='Tutores',
            new_name='Tutor',
        ),
    ]
