# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20160131_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/'),
        ),
    ]
