# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0001_initial'),
        ('pacientes', '0005_paciente_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='terapeutas',
            field=models.ManyToManyField(to='terapeutas.Terapeuta'),
        ),
    ]
