# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_terapeutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=12, null=True, verbose_name='telefono'),
        ),
    ]
