# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20160226_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2016, 2, 26), verbose_name='Fecha de ingreso'),
        ),
    ]
