# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20160226_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(b'LUNES', 'Lunes'), (b'MARTES', 'Martes'), (b'MIERCOLES', 'Miercoles'), (b'JUEVES', 'Jueves'), (b'VIERNES', 'Viernes'), (b'SABADO', 'Sabado'), (b'DOMINGO', 'Domingo')], max_length=9, verbose_name='dia')),
                ('hora_inicio', models.TimeField(max_length=255, verbose_name='Hora inicio')),
                ('hora_fin', models.CharField(max_length=9, unique=True, verbose_name='Hora fin')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
            },
        ),
    ]
