# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(max_length=5, verbose_name='Hora fin'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(max_length=5, verbose_name='Hora inicio'),
        ),
    ]
