# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0003_auto_20160226_0821'),
        ('pacientes', '0013_auto_20160226_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.FileField(upload_to=b'uploads/')),
                ('tipo', models.CharField(choices=[(b'Externo', 'Externo'), (b'Interno', 'Interno')], max_length=9, verbose_name='tipo')),
                ('fecha_informe', models.DateField(verbose_name='Fecha de informe')),
                ('fecha_entrega', models.DateField(default=datetime.date(2016, 2, 26), verbose_name='Fecha de entrega')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('terapeuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terapeutas.Terapeuta')),
            ],
            options={
                'verbose_name': 'informe',
                'verbose_name_plural': 'informes',
            },
        ),
    ]
