# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0020_auto_20160303_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre facturacion 1')),
                ('nif', models.CharField(max_length=9, verbose_name='NIF facturacion 1')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion facturacion 1')),
                ('cod_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo postal')),
                ('localidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='localidad')),
                ('provincia', models.CharField(blank=True, max_length=255, null=True, verbose_name='provincia')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'direccion facturacion',
                'verbose_name_plural': 'direcciones de facturacion',
            },
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date(2016, 3, 7), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2016, 3, 7), verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='direccion_facturacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
