# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0021_auto_20160307_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion_facturacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion facturacion'),
        ),
        migrations.AlterField(
            model_name='direccion_facturacion',
            name='nif',
            field=models.CharField(max_length=9, verbose_name='NIF facturacion'),
        ),
        migrations.AlterField(
            model_name='direccion_facturacion',
            name='nombre_completo',
            field=models.CharField(max_length=255, verbose_name='Nombre facturacion'),
        ),
    ]
