# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0022_auto_20160307_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[(b'ALTA', 'Alta'), (b'EN TRATAMIENTO', 'En tratamiento'), (b'OTRO', 'Otro')], default=b'En tratamiento', max_length=15, verbose_name='estado'),
        ),
    ]
