# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0026_auto_20160311_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='informe',
            field=models.FileField(upload_to=b''),
        ),
    ]
