# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0029_auto_20160314_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date(2016, 3, 15), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2016, 3, 15), verbose_name='Fecha de ingreso'),
        ),
    ]
