# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0030_auto_20160315_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date(2016, 3, 16), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2016, 3, 16), verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
