# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0033_auto_20160316_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
