# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0035_auto_20160318_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date(2016, 4, 5), verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2016, 4, 5), verbose_name='Fecha de ingreso'),
        ),
    ]
